### PR TITLE
Generate config file

### PR DESCRIPTION
**Pull request by sneak-it**

### CODE REVIEW

**Comment by t5mat** [comment]
Can we change to simply `AutoExecConfig();`?

**Comment by sneak-it** [comment]
> Can we change to simply `AutoExecConfig();`?

If for some reason the person renames the plugin source at the time of compile, then the config file name will not match the actual name of the plugin. I generally stay away from doing that in my plugins to ensure continuity.

**Comment by t5mat** [comment]
I prefer to go with the default behavior here - I think it's fine that the cfg's filename matches the plugin's filename (i.e. if plugin is renamed, a diferent cfg file is used). This also matches the behavior in rngfix, momsurffix

**Comment by sneak-it** [comment]
Sure, it's all personal preference. I'll adjust the PR next time I'm on a PC.

**Comment by sneak-it** [comment]
Should be all set now.

**Comment by t5mat** [comment]
Thanks, could you please squash the changes into 1 commit? :)

**Comment by sneak-it** [comment]
> Thanks, could you please squash the changes into 1 commit? :)

You can do that, it's a merge option right here on GitHub.

**Comment by t5mat** [comment]
prefer to keep branch history and just rebase, so I fixed it manually. thx for the PR!

**Pull request merged**
